In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [7]:
df = pd.read_csv("H:/Python In Data Science/HomePrices.csv")
df

Area  Prices
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [8]:
reg = linear_model.LinearRegression()
reg.fit(df[['Area']],df.Prices)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [9]:
reg.predict(5000)

array([859554.79452055])

In [11]:
import pickle # this API allow us to create our own portable training models 

In [12]:
with open('model_pickle_area','wb') as f: # 'wb' is for 'Write binqry' data and 'model_pickle_area' is Trained file name
    pickle.dump(reg,f) # dump my model in to the file mentioned above    

In [15]:
# we can read this model as below
with open('model_pickle_area','rb') as f: # we open that file in READ mode
    mp = pickle.load(f) # we have loded our file into memory and 'mp' is a object

In [16]:
#let's try...
mp.predict(5000)

array([859554.79452055])

In [18]:
# Check with JOBLIB
from sklearn.externals import joblib

In [19]:
joblib.dump(reg,'model_joblib_area') # Model has been created - check file location 

['model_joblib_area']

In [21]:
mj = joblib.load('model_joblib_area') # load file again and create an object 'mj' to access

In [23]:
mj.predict(5000)

array([859554.79452055])